### ISSUE TITLE
What is the sd in gaussian

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#10]
I don't understand the meaning of this sd parameter in the gaussian. What is the idea behind it ?

 * @param {number} [options.sd] - Standard deviation, if it's defined fwhm parameter will be ignored.

**Comment by jobo322** [comment]
fwhm and sd has a relationship of fwhm = 2 * sqrt( 2 * ln( 2 ) ). So we could define fwhm or sd. It could be removed.

**Comment by lpatiny** [comment]
Ok I see. I make sense to keep it. Just wonder if this is the right name for this parameter. SD means standard deviation. 

http://mathworld.wolfram.com/GaussianFunction.html

What is the name of this sigma parameter ?

![image](https://user-images.githubusercontent.com/1484241/75631697-618d8080-5bf5-11ea-991b-1a092e63cfd2.png)

**Comment by targos** [comment]
Sigma is the symbol used for standard deviation

**Comment by lpatiny** [comment]
I find it strange to enter sd=100 to have a width of 235 points while the surface at this width would
