### ISSUE TITLE
gaussian and expected area

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#11]
Not sure I understand well the parameters of gaussian.

If I add sd=1000 and factor=1, 2, 3 I expect as area to have:
- 0.6827
- 0.9545
- 0.9973

https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule

But this does not seam to be the case.

@jobo322 could you tell me I'm doing wrong ?

https://github.com/mljs/ml-peak-shape-generator/blob/e83ab31f59c141b95a9f76d6cee782cd6b70b9a8/src/__tests__/gaussian.test.js#L15

**Comment by jobo322** [comment]
At the moment the length of the shape is ( fwhm * factor + 1 ) so, the surface area for a factor equal 3 should be a little bit bigger than 3 * sd (0.9973) because of fwhm > sd. Currently, for a factor of 3, the area is 0.9996

**Comment by lpatiny** [comment]
But if I specify `sa` as in this testcase I'm expected to have the correct result no (meaning 3SD = 0.9973) ?

```
  it('sd fixed', () => {
    let data = gaussian({ sd: 2500 }).data;
    let area = 0;
    for (let i = 0; i < data.length - 1; i++) {
      area += data[i];
    }
    expect(area).toBeDeepCloseTo(0.9973, 5);
  });
```
