### ISSUE TITLE
factor should be calculated once for ever

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#31]
This code seems to be a copy / paste from pseudovoigt

https://github.com/mljs/ml-peak-shape-generator/blob/8865fc4dc8ef2f805808a081a3e86764310364d5/src/lorentzian.js#L17-L17

This should be calculated once for ever for a Lorentzian

**Comment by jobo322** [comment]
now there is a method for each instance that return a factor depending of an area required to be cover.
