### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by jobo322** [mljs/peak-shape-generator#42]
@targos in the process to migrate this package to typescript I face with [duplication of an identifier](https://github.com/mljs/peak-shape-generator/blob/master/src/classes/Gaussian.js#L57-L59). The idea is to be able to access some methods with/without instancing the class. Do you know if there is another design to get the same result?

**Comment by maasencioh** [comment]
If it's a static class method you don't need to instantiate the class, but why do you need the static and instance method?

**Comment by targos** [comment]
Anyway, static methods should be defined like this:

```
class X {
  static y() {}
}
```

Not with `X.y = function(){}`

**Comment by maasencioh** [comment]
For this specific case, I think that you could have something like this:

```ts
export class Gaussian {
  method1() {
    return method1();
  }
}

export function method1() {}
```

**Comment by jobo322** [comment]
Many thanks, In order to do not introduce a breaking change I'm doing something similar to:

```ts
constructor(options = {}) {
  const { fwhm, height } = options;
  this.fwhm = fwhm;
  this.height = height ;

  this.fct = (x) => Gaussian.fct(x, this.fwhm);
}

static fct(x: number, fwhm: number = 500) {
  return Math.exp(GAUSSIAN_EXP_FACTOR * Math.pow(x / fwhm, 2));
}
```

is it an acceptable way?

**Comment by targos** [comment]
what's the problem with:

```ts
constructor(options = {}) {
  const { fwhm, height } = options;
  this.fwhm = fwhm;
  this.height = height ;
}

static fct(x: number, fwhm: number = 500) {
  return Math.exp(GAUSSIAN_EXP_FACTOR * Math.pow(x / fwhm, 2));
}

fct(x: number) {
  return Gaussian.fct(x, this.fwhm)
}
```

**Comment by targos** [comment]
I would go further and do it like this:

Define the functions in separate file(s):

```ts
// Export these from the package so we can do `import { fct } from 'peak-shape-generator';`
export function fct(x: number, fwhm: number = 500) {
  return Math.exp(GAUSSIAN_EXP_FACTOR * Math.pow(x / fwhm, 2));
}
```

Then use it in the Gaussian class (keep the static method for backward-compat if you want):
```ts
import { fct } from './fct'

export class Gaussian {
  constructor(options = {}) {
    const { fwhm, height } = options;
    this.fwhm = fwhm;
    this.height = height ;
  }

  static fct(x: number, fwhm?: number) {
    return fct(x, fwhm);
  }

  fct(x: number) {
    return fct(x, this.fwhm)
  }
}
```

**Comment by jobo322** [comment]
I did try this way but I got errors. Luc suggest exporting functions like [spectra-processing](https://github.com/mljs/spectra-processing/tree/master/src). So I suggest having more or less the same function for each shape. So in the index export:

```ts
export * as gaussian from './shape/gaussian'
```
the file of a particular shape would be like [this](https://github.com/mljs/peak-shape-generator/blob/ts-migration/src/shapes/gaussian.ts).
