### ISSUE TITLE
Documentation, Math equation in @default tag

### ISSUE THREAD

**Issue by jobo322** [mljs/peak-shape-generator#43]
@targos what do you think about using math equations in the @default tag in the documentation. e.g:

![image](https://user-images.githubusercontent.com/12143935/127893715-30e7d186-3fbb-44b0-9584-245ed2bc74be.png)

**Comment by targos** [comment]
Is the question about using a math equation, or about using the default tagL

**Comment by jobo322** [comment]
Could be both and a combination of these. I mean the value of the default tag could be a math equation?

**Comment by targos** [comment]
I don't know. But I have no objection on adding math equations to the documentation if they help

**Comment by jobo322** [comment]
Thanks
