### ISSUE TITLE
Optimize the code

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#6]
Peaks are symmetric so please calculate only till the center: and fill both side of the shape at once. You need to do the limiting step calculation half of the time.

https://github.com/mljs/peak-shape-generator/blob/master/src/lorentzian.js#L16-L20

**Comment by jobo322** [comment]
It's done in https://github.com/mljs/peak-shape-generator/commit/e8c098479c9f2df4722dbfb8f5ca55f2b3c4df76

**Comment by jobo322** [comment]
@lpatiny What do you think about the factor parameter, should it a decimal number? or it could always be an integer?

**Comment by lpatiny** [comment]
I guess 1.5 make sense so it could be decimal except if too difficult to implement. Now is factor the best terminology ??
