### ISSUE TITLE
fwhm odd / even

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#7]
Deal correctly with odd /even peak width.

If odd number, this means that the center is the highest point and both side should have a lower value. This should be checked by a testcase.

If even number, this means that there are 2 'centers' that have the same height. This should be checked by a testcase.

**Comment by jobo322** [comment]
I understand SD and FWHM should always an integer, am I right?

**Comment by lpatiny** [comment]
fwhm for sure yes
sd not so sure. Maybe 1.5 make sense from time to time
