### ISSUE TITLE
Special kind of shapes ?

### ISSUE THREAD

**Issue by lpatiny** [mljs/peak-shape-generator#73]
Currently in this project we have 1D shapes that requires somehow to convert width to fwhm and reverse.

However we could think about another category of 1D shape that would be more general and solve the optimization of a doublet or triplets, etc.

@jobo322 this is something we should discuss.

**Comment by jobo322** [comment]
@lpatiny we have this [flexible signalsToXY](https://github.com/cheminfo/nmr-processing/blob/main/src/signals/hackSignalsToXY.ts) function that allows us to generate XY data from J-coupling data and multiplicities, we could use the code behind it to generate those kind of shapes from PSG
